spring:
  application:
    name: 사내문서QnA_메인실습

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

      chat:
        api-key: ${OPENAI_API_KEY}
        model: gpt-4o-mini

      embedding:
        api-key: ${OPENAI_API_KEY}
        model: text-embedding-3-small

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: none

logging:
  level:
    com.skala: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
